//Each new term in the Fibonacci sequence is generated by adding the previous two terms
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

package com.company;
public class Main
{
    public static void main(String[] args)
    {
//        int maxIntNumberCheck = Integer.MAX_VALUE;
//        System.out.println(maxIntNumberCheck);
//        System.out.println("It's 2147483647");

        int fibonacciIntegerOne = 1;
        int fibonacciIntegerTwo = 2;
        int sumOfEvenNumbers = 0;

        while(fibonacciIntegerOne+fibonacciIntegerTwo<4000000)
        {
            fibonacciIntegerOne=fibonacciIntegerOne+fibonacciIntegerTwo;
            if(fibonacciIntegerOne%2==0)
            {
                sumOfEvenNumbers = sumOfEvenNumbers + fibonacciIntegerOne;
               // System.out.println("Even number: "+fibonacciIntegerOne);
            }
            //System.out.println("fibonacciIntegerOne = "+fibonacciIntegerOne);
            fibonacciIntegerTwo=fibonacciIntegerTwo+fibonacciIntegerOne;
            if(fibonacciIntegerTwo%2==0)
            {
                sumOfEvenNumbers = sumOfEvenNumbers + fibonacciIntegerTwo;
               // System.out.println("Even number: "+fibonacciIntegerTwo);
            }
            //System.out.println("fibonacciIntegerTwo = "+fibonacciIntegerTwo);
        }
        System.out.println("sumOfEvenNumbers = "+sumOfEvenNumbers);

    }
}
